# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'FormTrogiup.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import res_rc


class Ui_FormTrogiup(object):
    def setupUi(self, FormTrogiup):
        FormTrogiup.setObjectName("FormTrogiup")
        FormTrogiup.resize(800, 500)
        FormTrogiup.setWindowFlags(QtCore.Qt.FramelessWindowHint)
        FormTrogiup.setAttribute(QtCore.Qt.WA_TranslucentBackground)
        FormTrogiup.setStyleSheet("QPushButton#bt_back{\n"
"background-color:rgba(2,65,118,255);\n"
"color:rgba(255,255,255,200);\n"
"border-radius:5px;\n"
"}\n"
"QPushButton#bt_back:pressed{\n"
"padding-left:5px;\n"
"padding-top:5px;\n"
"background-color:rgba(2,65,118,100);\n"
"background-position:calc(100%-10px)center;\n"
"}\n"
"QPushButton#bt_back:hover{\n"
"background-color:rgba(2,65,118,200);\n"
"}")
        self.label = QtWidgets.QLabel(FormTrogiup)
        self.label.setGeometry(QtCore.QRect(0, 0, 800, 500))
        self.label.setStyleSheet("border-image: url(:/backgroud/backgroud/1912279.jpg);\n"
"border - radius: 5px;")
        self.label.setText("")
        self.label.setObjectName("label")
        self.bt_back = QtWidgets.QPushButton(FormTrogiup)
        self.bt_back.setGeometry(QtCore.QRect(30, 30, 81, 31))
        font = QtGui.QFont()
        font.setFamily("UVN Dzung Dakao")
        font.setItalic(True)
        self.bt_back.setFont(font)
        self.bt_back.setObjectName("bt_back")
        self.label_2 = QtWidgets.QLabel(FormTrogiup)
        self.label_2.setGeometry(QtCore.QRect(160, 90, 631, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: rgb(255, 255, 0);")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(FormTrogiup)
        self.label_3.setGeometry(QtCore.QRect(240, 130, 511, 271))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(False)
        font.setWeight(50)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color: rgb(0, 85, 0);")
        self.label_3.setObjectName("label_3")

        self.retranslateUi(FormTrogiup)
        QtCore.QMetaObject.connectSlotsByName(FormTrogiup)

    def retranslateUi(self, FormTrogiup):
        _translate = QtCore.QCoreApplication.translate
        FormTrogiup.setWindowTitle(_translate("FormTrogiup", "Form"))
        self.bt_back.setText(_translate("FormTrogiup", "Back"))
        self.label_2.setText(_translate("FormTrogiup", "Mọi trục trặc hoặc sự cố vui lòng liên hệ:"))
        self.label_3.setText(_translate("FormTrogiup", "Hotline: 66771508\n"
"Gmail: Thaitbkka@gmail.com\n"
"OR\n"
"Mr.Thai: Infor\n"
"Mr.Thanh:Infor\n"
"Mr.Hiep: Infor"))
import res_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    FormTrogiup = QtWidgets.QWidget()
    ui = Ui_FormTrogiup()
    ui.setupUi(FormTrogiup)
    FormTrogiup.show()
    sys.exit(app.exec_())
