# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'FormMainmenu.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form_Mainmenu(object):
    def setupUi(self, Form_Mainmenu):
        Form_Mainmenu.setObjectName("Form_Mainmenu")
        Form_Mainmenu.resize(800, 500)
        Form_Mainmenu.setWindowFlags(QtCore.Qt.FramelessWindowHint)
        Form_Mainmenu.setAttribute(QtCore.Qt.WA_TranslucentBackground)
        Form_Mainmenu.setStyleSheet("QPushButton#bt_diemdanh{\n"
"background-color:rgba(2,65,118,255);\n"
"color:rgba(255,255,255,200);\n"
"border-radius:5px;\n"
"}\n"
"QPushButton#bt_diemdanh:pressed{\n"
"padding-left:5px;\n"
"padding-top:5px;\n"
"background-color:rgba(2,65,118,100);\n"
"background-position:calc(100%-10px)center;\n"
"}\n"
"QPushButton#bt_diemdanh:hover{\n"
"background-color:rgba(2,65,118,200);\n"
"}\n"
"QPushButton#bt_trogiup{\n"
"background-color:rgba(2,65,118,255);\n"
"color:rgba(255,255,255,200);\n"
"border-radius:5px;\n"
"}\n"
"QPushButton#bt_trogiup:pressed{\n"
"padding-left:5px;\n"
"padding-top:5px;\n"
"background-color:rgba(2,65,118,100);\n"
"background-position:calc(100%-10px)center;\n"
"}\n"
"QPushButton#bt_trogiup:hover{\n"
"background-color:rgba(2,65,118,200);\n"
"}\n"
"QPushButton#bt_thongtin{\n"
"background-color:rgba(2,65,118,255);\n"
"color:rgba(255,255,255,200);\n"
"border-radius:5px;\n"
"}\n"
"QPushButton#bt_thongtin:pressed{\n"
"padding-left:5px;\n"
"padding-top:5px;\n"
"background-color:rgba(2,65,118,100);\n"
"background-position:calc(100%-10px)center;\n"
"}\n"
"QPushButton#bt_thongtin:hover{\n"
"background-color:rgba(2,65,118,200);\n"
"}\n"
"QPushButton#bt_admin{\n"
"background-color:rgba(2,65,118,255);\n"
"color:rgba(255,255,255,200);\n"
"border-radius:5px;\n"
"}\n"
"QPushButton#bt_admin:pressed{\n"
"padding-left:5px;\n"
"padding-top:5px;\n"
"background-color:rgba(2,65,118,100);\n"
"background-position:calc(100%-10px)center;\n"
"}\n"
"QPushButton#bt_admin:hover{\n"
"background-color:rgba(2,65,118,200);\n"
"}\n"
"QPushButton#bt_thoat{\n"
"background-color:rgba(2,65,118,255);\n"
"color:rgba(255,255,255,200);\n"
"border-radius:5px;\n"
"}\n"
"QPushButton#bt_thoat:pressed{\n"
"padding-left:5px;\n"
"padding-top:5px;\n"
"background-color:rgba(2,65,118,100);\n"
"background-position:calc(100%-10px)center;\n"
"}\n"
"QPushButton#bt_thoat:hover{\n"
"background-color:rgba(2,65,118,200);\n"
"}")
        self.label = QtWidgets.QLabel(Form_Mainmenu)
        self.label.setGeometry(QtCore.QRect(0, 0, 800, 500))
        self.label.setStyleSheet("border-image: url(:/backgroud/backgroud/b8.jpg);\n"
"border-radius:5px;")
        self.label.setText("")
        self.label.setObjectName("label")
        self.bt_thoat = QtWidgets.QPushButton(Form_Mainmenu)
        self.bt_thoat.setGeometry(QtCore.QRect(30, 30, 93, 28))
        font = QtGui.QFont()
        font.setFamily("UVN Dzung Dakao")
        font.setPointSize(10)
        font.setItalic(True)
        self.bt_thoat.setFont(font)
        self.bt_thoat.setObjectName("bt_thoat")
        self.bt_diemdanh = QtWidgets.QPushButton(Form_Mainmenu)
        self.bt_diemdanh.setGeometry(QtCore.QRect(340, 200, 120, 35))
        font = QtGui.QFont()
        font.setFamily("UVN Dzung Dakao")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.bt_diemdanh.setFont(font)
        self.bt_diemdanh.setObjectName("bt_diemdanh")
        self.bt_trogiup = QtWidgets.QPushButton(Form_Mainmenu)
        self.bt_trogiup.setGeometry(QtCore.QRect(340, 260, 120, 35))
        font = QtGui.QFont()
        font.setFamily("UVN Dzung Dakao")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.bt_trogiup.setFont(font)
        self.bt_trogiup.setObjectName("bt_trogiup")
        self.bt_thongtin = QtWidgets.QPushButton(Form_Mainmenu)
        self.bt_thongtin.setGeometry(QtCore.QRect(340, 330, 120, 35))
        font = QtGui.QFont()
        font.setFamily("UVN Dzung Dakao")
        font.setPointSize(10)
        font.setItalic(True)
        self.bt_thongtin.setFont(font)
        self.bt_thongtin.setObjectName("bt_thongtin")
        self.bt_admin = QtWidgets.QPushButton(Form_Mainmenu)
        self.bt_admin.setGeometry(QtCore.QRect(340, 410, 120, 35))
        font = QtGui.QFont()
        font.setFamily("UVN Dzung Dakao")
        font.setPointSize(10)
        font.setItalic(True)
        self.bt_admin.setFont(font)
        self.bt_admin.setObjectName("bt_admin")
        self.label_2 = QtWidgets.QLabel(Form_Mainmenu)
        self.label_2.setGeometry(QtCore.QRect(180, 70, 501, 51))
        font = QtGui.QFont()
        font.setFamily("UVN Dzung Dakao")
        font.setPointSize(20)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color:rgb(255, 255, 0)")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Form_Mainmenu)
        self.label_3.setGeometry(QtCore.QRect(230, 130, 391, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")

        self.retranslateUi(Form_Mainmenu)
        QtCore.QMetaObject.connectSlotsByName(Form_Mainmenu)

    def retranslateUi(self, Form_Mainmenu):
        _translate = QtCore.QCoreApplication.translate
        Form_Mainmenu.setWindowTitle(_translate("Form_Mainmenu", "Form"))
        self.bt_thoat.setText(_translate("Form_Mainmenu", "Thoát"))
        self.bt_diemdanh.setText(_translate("Form_Mainmenu", "Điểm danh"))
        self.bt_trogiup.setText(_translate("Form_Mainmenu", "Trợ giúp"))
        self.bt_thongtin.setText(_translate("Form_Mainmenu", "Thông tin "))
        self.bt_admin.setText(_translate("Form_Mainmenu", "Chế độ Admin"))
        self.label_2.setText(_translate("Form_Mainmenu", "ỨNG DỤNG ĐIỂM DANH KMA"))
        self.label_3.setText(_translate("Form_Mainmenu", "KMA attendance management"))
import res_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form_Mainmenu = QtWidgets.QWidget()
    ui = Ui_Form_Mainmenu()
    ui.setupUi(Form_Mainmenu)
    Form_Mainmenu.show()
    sys.exit(app.exec_())
