# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'FormUpdate1.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_FormUpdate1(object):
    def setupUi(self, FormUpdate1):
        FormUpdate1.setObjectName("FormUpdate1")
        FormUpdate1.resize(800, 500)
        FormUpdate1.setWindowFlags(QtCore.Qt.FramelessWindowHint)
        FormUpdate1.setAttribute(QtCore.Qt.WA_TranslucentBackground)
        font = QtGui.QFont()
        font.setFamily("UVN Dzung Dakao")
        font.setPointSize(10)
        font.setItalic(True)
        FormUpdate1.setFont(font)
        FormUpdate1.setStyleSheet("QPushButton#bt_hienthi{\n"
"background-color:rgba(2,65,118,255);\n"
"color:rgba(255,255,255,200);\n"
"border-radius:5px;\n"
"}\n"
"QPushButton#bt_hienthi:pressed{\n"
"padding-left:5px;\n"
"padding-top:5px;\n"
"background-color:rgba(2,65,118,100);\n"
"background-position:calc(100%-10px)center;\n"
"}\n"
"QPushButton#bt_hienthi:hover{\n"
"background-color:rgba(2,65,118,200);\n"
"}\n"
"QPushButton#bt_capnhat{\n"
"background-color:rgba(2,65,118,255);\n"
"color:rgba(255,255,255,200);\n"
"border-radius:5px;\n"
"}\n"
"QPushButton#bt_capnhat:pressed{\n"
"padding-left:5px;\n"
"padding-top:5px;\n"
"background-color:rgba(2,65,118,100);\n"
"background-position:calc(100%-10px)center;\n"
"}\n"
"QPushButton#bt_capnhat:hover{\n"
"background-color:rgba(2,65,118,200);\n"
"}\n"
"QPushButton#bt_thoat{\n"
"background-color:rgba(2,65,118,255);\n"
"color:rgba(255,255,255,200);\n"
"border-radius:5px;\n"
"}\n"
"QPushButton#bt_thoat:pressed{\n"
"padding-left:5px;\n"
"padding-top:5px;\n"
"background-color:rgba(2,65,118,100);\n"
"background-position:calc(100%-10px)center;\n"
"}\n"
"QPushButton#bt_thoat:hover{\n"
"background-color:rgba(2,65,118,200);\n"
"}\n"
"QPushButton#bt_timkiem{\n"
"background-color:rgba(2,65,118,255);\n"
"color:rgba(255,255,255,200);\n"
"border-radius:5px;\n"
"}\n"
"QPushButton#bt_timkiem:pressed{\n"
"padding-left:5px;\n"
"padding-top:5px;\n"
"background-color:rgba(2,65,118,100);\n"
"background-position:calc(100%-10px)center;\n"
"}\n"
"QPushButton#bt_timkiem:hover{\n"
"background-color:rgba(2,65,118,200);\n"
"}")
        self.label = QtWidgets.QLabel(FormUpdate1)
        self.label.setGeometry(QtCore.QRect(0, 0, 800, 500))
        self.label.setStyleSheet("border-image:url(:/backgroud/backgroud/futuristic_cpu.jpg);\n"
"border-radius:5px;")
        self.label.setText("")
        self.label.setObjectName("label")
        self.tableWidget = QtWidgets.QTableWidget(FormUpdate1)
        self.tableWidget.setGeometry(QtCore.QRect(20, 100, 481, 341))
        self.tableWidget.setStyleSheet("")
        self.tableWidget.setRowCount(0)
        self.tableWidget.setColumnCount(6)
        self.tableWidget.setObjectName("tableWidget")
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        self.label_2 = QtWidgets.QLabel(FormUpdate1)
        self.label_2.setGeometry(QtCore.QRect(20, 70, 241, 21))
        font = QtGui.QFont()
        font.setFamily("UVN Dzung Dakao")
        font.setPointSize(12)
        font.setItalic(True)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: rgb(255, 255, 0);")
        self.label_2.setObjectName("label_2")
        self.bt_hienthi = QtWidgets.QPushButton(FormUpdate1)
        self.bt_hienthi.setGeometry(QtCore.QRect(130, 450, 231, 28))
        font = QtGui.QFont()
        font.setFamily("UVN Dzung Dakao")
        font.setPointSize(10)
        font.setItalic(True)
        self.bt_hienthi.setFont(font)
        self.bt_hienthi.setObjectName("bt_hienthi")
        self.bt_capnhat = QtWidgets.QPushButton(FormUpdate1)
        self.bt_capnhat.setGeometry(QtCore.QRect(570, 420, 171, 28))
        font = QtGui.QFont()
        font.setFamily("UVN Dzung Dakao")
        font.setPointSize(10)
        font.setItalic(True)
        self.bt_capnhat.setFont(font)
        self.bt_capnhat.setObjectName("bt_capnhat")
        self.bt_thoat = QtWidgets.QPushButton(FormUpdate1)
        self.bt_thoat.setGeometry(QtCore.QRect(680, 460, 93, 28))
        font = QtGui.QFont()
        font.setFamily("UVN Dzung Dakao")
        font.setPointSize(10)
        font.setItalic(True)
        self.bt_thoat.setFont(font)
        self.bt_thoat.setObjectName("bt_thoat")
        self.error = QtWidgets.QLabel(FormUpdate1)
        self.error.setGeometry(QtCore.QRect(550, 370, 231, 41))
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.error.setFont(font)
        self.error.setStyleSheet("color: rgb(255, 255, 0);")
        self.error.setText("")
        self.error.setObjectName("error")
        self.label_3 = QtWidgets.QLabel(FormUpdate1)
        self.label_3.setGeometry(QtCore.QRect(480, 10, 311, 91))
        self.label_3.setStyleSheet("background-color:rgba(0,0,0,75);")
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.label_5 = QtWidgets.QLabel(FormUpdate1)
        self.label_5.setGeometry(QtCore.QRect(490, 0, 171, 51))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("color: rgb(255, 255, 0);")
        self.label_5.setObjectName("label_5")
        self.line_id_2 = QtWidgets.QLineEdit(FormUpdate1)
        self.line_id_2.setGeometry(QtCore.QRect(490, 40, 180, 25))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.line_id_2.setFont(font)
        self.line_id_2.setStyleSheet("background-color:rgba(0,0,0,0);\n"
"border:none;\n"
"border-bottom:2px solid rgba(46,82,101,200);\n"
"color: rgb(255, 255, 0);\n"
"padding-bottom:7px;")
        self.line_id_2.setObjectName("line_id_2")
        self.error_2 = QtWidgets.QLabel(FormUpdate1)
        self.error_2.setGeometry(QtCore.QRect(480, 70, 211, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.error_2.setFont(font)
        self.error_2.setStyleSheet("color: rgb(255, 255, 0);")
        self.error_2.setText("")
        self.error_2.setObjectName("error_2")
        self.bt_timkiem = QtWidgets.QPushButton(FormUpdate1)
        self.bt_timkiem.setGeometry(QtCore.QRect(680, 40, 101, 28))
        font = QtGui.QFont()
        font.setFamily("UVN Dzung Dakao")
        font.setPointSize(10)
        font.setItalic(True)
        self.bt_timkiem.setFont(font)
        self.bt_timkiem.setObjectName("bt_timkiem")
        self.label_6 = QtWidgets.QLabel(FormUpdate1)
        self.label_6.setGeometry(QtCore.QRect(540, 120, 241, 291))
        self.label_6.setStyleSheet("background-color:rgba(0,0,0,75);")
        self.label_6.setText("")
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(FormUpdate1)
        self.label_7.setGeometry(QtCore.QRect(590, 120, 161, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("color: rgb(255, 255, 0);")
        self.label_7.setObjectName("label_7")
        self.line_id = QtWidgets.QLineEdit(FormUpdate1)
        self.line_id.setGeometry(QtCore.QRect(570, 150, 180, 25))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.line_id.setFont(font)
        self.line_id.setStyleSheet("background-color:rgba(0,0,0,0);\n"
"border:none;\n"
"border-bottom:2px solid rgba(46,82,101,200);\n"
"color:rgba(0,0,0,240);\n"
"padding-bottom:7px;")
        self.line_id.setObjectName("line_id")
        self.line_name = QtWidgets.QLineEdit(FormUpdate1)
        self.line_name.setGeometry(QtCore.QRect(570, 190, 180, 25))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.line_name.setFont(font)
        self.line_name.setStyleSheet("background-color:rgba(0,0,0,0);\n"
"border:none;\n"
"border-bottom:2px solid rgba(46,82,101,200);\n"
"color:rgba(0,0,0,240);\n"
"padding-bottom:7px;\n"
"")
        self.line_name.setObjectName("line_name")
        self.line_age = QtWidgets.QLineEdit(FormUpdate1)
        self.line_age.setGeometry(QtCore.QRect(570, 220, 180, 25))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.line_age.setFont(font)
        self.line_age.setStyleSheet("background-color:rgba(0,0,0,0);\n"
"border:none;\n"
"border-bottom:2px solid rgba(46,82,101,200);\n"
"color:rgba(0,0,0,240);\n"
"padding-bottom:7px;")
        self.line_age.setObjectName("line_age")
        self.line_gender = QtWidgets.QLineEdit(FormUpdate1)
        self.line_gender.setGeometry(QtCore.QRect(570, 260, 180, 25))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.line_gender.setFont(font)
        self.line_gender.setStyleSheet("background-color:rgba(0,0,0,0);\n"
"border:none;\n"
"border-bottom:2px solid rgba(46,82,101,200);\n"
"color:rgba(0,0,0,240);\n"
"padding-bottom:7px;")
        self.line_gender.setObjectName("line_gender")
        self.line_phone = QtWidgets.QLineEdit(FormUpdate1)
        self.line_phone.setGeometry(QtCore.QRect(570, 300, 180, 25))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.line_phone.setFont(font)
        self.line_phone.setStyleSheet("background-color:rgba(0,0,0,0);\n"
"border:none;\n"
"border-bottom:2px solid rgba(46,82,101,200);\n"
"color:rgba(0,0,0,240);\n"
"padding-bottom:7px;")
        self.line_phone.setObjectName("line_phone")
        self.line_address = QtWidgets.QLineEdit(FormUpdate1)
        self.line_address.setGeometry(QtCore.QRect(570, 340, 180, 25))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.line_address.setFont(font)
        self.line_address.setStyleSheet("background-color:rgba(0,0,0,0);\n"
"border:none;\n"
"border-bottom:2px solid rgba(46,82,101,200);\n"
"color:rgba(0,0,0,240);\n"
"padding-bottom:7px;")
        self.line_address.setObjectName("line_address")

        self.retranslateUi(FormUpdate1)
        QtCore.QMetaObject.connectSlotsByName(FormUpdate1)

    def retranslateUi(self, FormUpdate1):
        _translate = QtCore.QCoreApplication.translate
        FormUpdate1.setWindowTitle(_translate("FormUpdate1", "Form"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("FormUpdate1", "ID"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("FormUpdate1", "Họ và Tên "))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("FormUpdate1", "Tuổi"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("FormUpdate1", "Giới Tính"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("FormUpdate1", "SĐT"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("FormUpdate1", "Địa Chỉ"))
        self.label_2.setText(_translate("FormUpdate1", "Danh sách sinh viên:"))
        self.bt_hienthi.setText(_translate("FormUpdate1", "Hiển thị danh sách"))
        self.bt_capnhat.setText(_translate("FormUpdate1", "Cập nhật thông tin"))
        self.bt_thoat.setText(_translate("FormUpdate1", "Thoát"))
        self.label_5.setText(_translate("FormUpdate1", "Nhập ID đối tượng cần tìm"))
        self.line_id_2.setPlaceholderText(_translate("FormUpdate1", "ID"))
        self.bt_timkiem.setText(_translate("FormUpdate1", "Tìm kiếm"))
        self.label_7.setText(_translate("FormUpdate1", "Bảng cập nhật thông tin"))
        self.line_id.setPlaceholderText(_translate("FormUpdate1", "ID"))
        self.line_name.setPlaceholderText(_translate("FormUpdate1", "Name"))
        self.line_age.setPlaceholderText(_translate("FormUpdate1", "Age"))
        self.line_gender.setPlaceholderText(_translate("FormUpdate1", "Gender"))
        self.line_phone.setPlaceholderText(_translate("FormUpdate1", "Phone"))
        self.line_address.setPlaceholderText(_translate("FormUpdate1", "Address"))
import res_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    FormUpdate1 = QtWidgets.QWidget()
    ui = Ui_FormUpdate1()
    ui.setupUi(FormUpdate1)
    FormUpdate1.show()
    sys.exit(app.exec_())
