# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'FormXemlich.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form_Xemlich(object):
    def setupUi(self, Form_Xemlich):
        Form_Xemlich.setObjectName("Form_Xemlich")
        Form_Xemlich.resize(800, 500)
        Form_Xemlich.setWindowFlags(QtCore.Qt.FramelessWindowHint)
        Form_Xemlich.setAttribute(QtCore.Qt.WA_TranslucentBackground)
        Form_Xemlich.setStyleSheet("QPushButton#bt_back{\n"
"background-color:rgba(2,65,118,255);\n"
"color:rgba(255,255,255,200);\n"
"border-radius:5px;\n"
"}\n"
"QPushButton#bt_back:pressed{\n"
"padding-left:5px;\n"
"padding-top:5px;\n"
"background-color:rgba(2,65,118,100);\n"
"background-position:calc(100%-10px)center;\n"
"}\n"
"QPushButton#bt_back:hover{\n"
"background-color:rgba(2,65,118,200);\n"
"}\n"
"QPushButton#bt_hienthi{\n"
"background-color:rgba(2,65,118,255);\n"
"color:rgba(255,255,255,200);\n"
"border-radius:5px;\n"
"}\n"
"QPushButton#bt_hienthi:pressed{\n"
"padding-left:5px;\n"
"padding-top:5px;\n"
"background-color:rgba(2,65,118,100);\n"
"background-position:calc(100%-10px)center;\n"
"}\n"
"QPushButton#bt_hienthi:hover{\n"
"background-color:rgba(2,65,118,200);\n"
"}")
        self.label = QtWidgets.QLabel(Form_Xemlich)
        self.label.setGeometry(QtCore.QRect(0, 0, 800, 500))
        self.label.setStyleSheet("border-image: url(:/backgroud/backgroud/b6.jpg);\n"
"border-radius:5px;")
        self.label.setText("")
        self.label.setObjectName("label")
        self.bt_hienthi = QtWidgets.QPushButton(Form_Xemlich)
        self.bt_hienthi.setGeometry(QtCore.QRect(650, 120, 93, 28))
        font = QtGui.QFont()
        font.setFamily("UVN Dzung Dakao")
        font.setPointSize(10)
        font.setItalic(True)
        self.bt_hienthi.setFont(font)
        self.bt_hienthi.setObjectName("bt_hienthi")
        self.tableWidget = QtWidgets.QTableWidget(Form_Xemlich)
        self.tableWidget.setGeometry(QtCore.QRect(10, 110, 621, 371))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(5)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        self.bt_back = QtWidgets.QPushButton(Form_Xemlich)
        self.bt_back.setGeometry(QtCore.QRect(10, 30, 93, 28))
        font = QtGui.QFont()
        font.setFamily("UVN Dzung Dakao")
        font.setPointSize(10)
        font.setItalic(True)
        self.bt_back.setFont(font)
        self.bt_back.setObjectName("bt_back")

        self.retranslateUi(Form_Xemlich)
        QtCore.QMetaObject.connectSlotsByName(Form_Xemlich)

    def retranslateUi(self, Form_Xemlich):
        _translate = QtCore.QCoreApplication.translate
        Form_Xemlich.setWindowTitle(_translate("Form_Xemlich", "Form"))
        self.bt_hienthi.setText(_translate("Form_Xemlich", "Hiển thị"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Form_Xemlich", "Họ và Tên"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Form_Xemlich", "ID"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("Form_Xemlich", "Giờ"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("Form_Xemlich", "Ngày"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("Form_Xemlich", "Trạng Thái"))
        self.bt_back.setText(_translate("Form_Xemlich", "Back"))
import res_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form_Xemlich = QtWidgets.QWidget()
    ui = Ui_Form_Xemlich()
    ui.setupUi(Form_Xemlich)
    Form_Xemlich.show()
    sys.exit(app.exec_())
