# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'FormThongtin.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import res_rc


class Ui_FormThongtin(object):
    def setupUi(self, FormThongtin):
        FormThongtin.setObjectName("FormThongtin")
        FormThongtin.resize(800, 500)
        FormThongtin.setWindowFlags(QtCore.Qt.FramelessWindowHint)
        FormThongtin.setAttribute(QtCore.Qt.WA_TranslucentBackground)
        FormThongtin.setStyleSheet("QPushButton#bt_back{\n"
"background-color:rgba(2,65,118,255);\n"
"color:rgba(255,255,255,200);\n"
"border-radius:5px;\n"
"}\n"
"QPushButton#bt_back:pressed{\n"
"padding-left:5px;\n"
"padding-top:5px;\n"
"background-color:rgba(2,65,118,100);\n"
"background-position:calc(100%-10px)center;\n"
"}\n"
"QPushButton#bt_back:hover{\n"
"background-color:rgba(2,65,118,200);\n"
"}")
        self.label = QtWidgets.QLabel(FormThongtin)
        self.label.setGeometry(QtCore.QRect(0, 0, 800, 500))
        self.label.setStyleSheet("background-image: url(:/backgroud/backgroud/8852.jpg_wh860.jpg);\n"
"border - radius: 5px;")
        self.label.setText("")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(FormThongtin)
        self.label_2.setGeometry(QtCore.QRect(390, 160, 55, 16))
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(FormThongtin)
        self.label_3.setGeometry(QtCore.QRect(140, 130, 591, 51))
        font = QtGui.QFont()
        font.setFamily(".Vn3DH")
        font.setPointSize(15)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(FormThongtin)
        self.label_4.setGeometry(QtCore.QRect(360, 220, 161, 21))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(FormThongtin)
        self.label_5.setGeometry(QtCore.QRect(140, 270, 591, 31))
        font = QtGui.QFont()
        font.setFamily(".Vn3DH")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(FormThongtin)
        self.label_6.setGeometry(QtCore.QRect(360, 340, 201, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.bt_back = QtWidgets.QPushButton(FormThongtin)
        self.bt_back.setGeometry(QtCore.QRect(40, 30, 81, 31))
        font = QtGui.QFont()
        font.setFamily("UVN Dzung Dakao")
        font.setItalic(True)
        self.bt_back.setFont(font)
        self.bt_back.setObjectName("bt_back")

        self.retranslateUi(FormThongtin)
        QtCore.QMetaObject.connectSlotsByName(FormThongtin)

    def retranslateUi(self, FormThongtin):
        _translate = QtCore.QCoreApplication.translate
        FormThongtin.setWindowTitle(_translate("FormThongtin", "Form"))
        self.label_3.setText(_translate("FormThongtin", " KMA attendance management!"))
        self.label_4.setText(_translate("FormThongtin", "version 1.0.1"))
        self.label_5.setText(_translate("FormThongtin", "Developed by Group 98 (The boss)"))
        self.label_6.setText(_translate("FormThongtin", "actvn.edu.vn"))
        self.bt_back.setText(_translate("FormThongtin", "Back"))
import res_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    FormThongtin = QtWidgets.QWidget()
    ui = Ui_FormThongtin()
    ui.setupUi(FormThongtin)
    FormThongtin.show()
    sys.exit(app.exec_())
