# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'FormLogin.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form_Login(object):
    def setupUi(self, Form_Login):
        Form_Login.setObjectName("Form_Login")
        Form_Login.resize(548, 499)
        Form_Login.setWindowFlags(QtCore.Qt.FramelessWindowHint)
        Form_Login.setAttribute(QtCore.Qt.WA_TranslucentBackground)
        self.widget = QtWidgets.QWidget(Form_Login)
        self.widget.setGeometry(QtCore.QRect(0, 0, 550, 500))
        self.widget.setStyleSheet("QPushButton#bt_login{\n"
"background-color:rgba(2,65,118,255);\n"
"color:rgba(255,255,255,200);\n"
"border-radius:5px;\n"
"}\n"
"QPushButton#bt_login:pressed{\n"
"padding-left:5px;\n"
"padding-top:5px;\n"
"background-color:rgba(2,65,118,100);\n"
"background-position:calc(100%-10px)center;\n"
"}\n"
"QPushButton#bt_back:hover{\n"
"background-color:rgba(2,65,118,200);\n"
"}\n"
"QPushButton#bt_back{\n"
"background-color:rgba(2,65,118,255);\n"
"color:rgba(255,255,255,200);\n"
"border-radius:5px;\n"
"}\n"
"QPushButton#bt_back:pressed{\n"
"padding-left:5px;\n"
"padding-top:5px;\n"
"background-color:rgba(2,65,118,100);\n"
"background-position:calc(100%-10px)center;\n"
"}\n"
"QPushButton#bt_back:hover{\n"
"background-color:rgba(2,65,118,200);\n"
"}")
        self.widget.setObjectName("widget")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setGeometry(QtCore.QRect(40, 30, 280, 430))
        self.label.setStyleSheet("\n"
"border-image:url(:/backgroud/backgroud/b9.jpg);\n"
"border-top-left-radius:50px;")
        self.label.setText("")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setGeometry(QtCore.QRect(270, 30, 240, 430))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("background-color:rgba(255, 255, 255);\n"
"border-bottom-right-radius:50px;")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.widget)
        self.label_3.setGeometry(QtCore.QRect(300, 70, 181, 41))
        font = QtGui.QFont()
        font.setFamily("UVN Dzung Dakao")
        font.setPointSize(20)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color:rgba(0,0,0,200);")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.widget)
        self.label_4.setGeometry(QtCore.QRect(350, 120, 71, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.line_username = QtWidgets.QLineEdit(self.widget)
        self.line_username.setGeometry(QtCore.QRect(295, 180, 190, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.line_username.setFont(font)
        self.line_username.setStyleSheet("background-color:rgba(0,0,0,0);\n"
"border:none;\n"
"border-bottom:2px solid rgba(46,82,101,200);\n"
"color:rgba(0,0,0,240);\n"
"padding-bottom:7px;\n"
"")
        self.line_username.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.line_username.setObjectName("line_username")
        self.line_password = QtWidgets.QLineEdit(self.widget)
        self.line_password.setGeometry(QtCore.QRect(295, 255, 190, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.line_password.setFont(font)
        self.line_password.setStyleSheet("background-color:rgba(0,0,0,0);\n"
"border:none;\n"
"border-bottom:2px solid rgba(46,82,101,200);\n"
"color:rgba(0,0,0,240);\n"
"padding-bottom:7px;\n"
"")
        self.line_password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.line_password.setObjectName("line_password")
        self.bt_login = QtWidgets.QPushButton(self.widget)
        self.bt_login.setGeometry(QtCore.QRect(330, 370, 93, 28))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.bt_login.setFont(font)
        self.bt_login.setObjectName("bt_login")
        self.label_5 = QtWidgets.QLabel(self.widget)
        self.label_5.setGeometry(QtCore.QRect(40, 80, 230, 130))
        self.label_5.setStyleSheet("background-color:rgba(0,0,0,75);")
        self.label_5.setText("")
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.widget)
        self.label_6.setGeometry(QtCore.QRect(50, 120, 81, 51))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setItalic(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.widget)
        self.label_7.setGeometry(QtCore.QRect(130, 110, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("color: rgb(255, 255, 255);\n"
"")
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.widget)
        self.label_8.setGeometry(QtCore.QRect(150, 150, 121, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setStyleSheet("color: rgb(255, 255, 255);\n"
"")
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.widget)
        self.label_9.setGeometry(QtCore.QRect(40, 210, 221, 101))
        self.label_9.setStyleSheet("color: rgb(255, 255, 0);\n"
"background-color:rgba(0,0,0,75);")
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.widget)
        self.label_10.setGeometry(QtCore.QRect(280, 420, 191, 31))
        font = QtGui.QFont()
        font.setItalic(True)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.bt_back = QtWidgets.QPushButton(self.widget)
        self.bt_back.setGeometry(QtCore.QRect(50, 420, 71, 21))
        font = QtGui.QFont()
        font.setFamily("UVN Dzung Dakao")
        font.setItalic(True)
        self.bt_back.setFont(font)
        self.bt_back.setObjectName("bt_back")
        self.error = QtWidgets.QLabel(self.widget)
        self.error.setGeometry(QtCore.QRect(290, 310, 191, 41))
        font = QtGui.QFont()
        font.setItalic(True)
        self.error.setFont(font)
        self.error.setStyleSheet("color: rgb(255, 0, 0);")
        self.error.setText("")
        self.error.setObjectName("error")

        self.retranslateUi(Form_Login)
        QtCore.QMetaObject.connectSlotsByName(Form_Login)

    def retranslateUi(self, Form_Login):
        _translate = QtCore.QCoreApplication.translate
        Form_Login.setWindowTitle(_translate("Form_Login", "Form"))
        self.label_3.setText(_translate("Form_Login", "Đăng nhập"))
        self.label_4.setText(_translate("Form_Login", "(Log In)"))
        self.line_username.setPlaceholderText(_translate("Form_Login", "Username"))
        self.line_password.setPlaceholderText(_translate("Form_Login", "Password"))
        self.bt_login.setText(_translate("Form_Login", "Log In"))
        self.label_6.setText(_translate("Form_Login", "KMA"))
        self.label_7.setText(_translate("Form_Login", "attendance"))
        self.label_8.setText(_translate("Form_Login", "management"))
        self.label_9.setText(_translate("Form_Login", "Xin chào,\n"
"Đây là ứng dụng quản lý điểm danh\n"
"Hãy đăng nhập để vào chế độ quản lý"))
        self.label_10.setText(_translate("Form_Login", "Chế độ này chỉ dành cho quản lý\n"
"hoặc nhân viên kỹ thuật"))
        self.bt_back.setText(_translate("Form_Login", "Back"))
import res_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form_Login = QtWidgets.QWidget()
    ui = Ui_Form_Login()
    ui.setupUi(Form_Login)
    Form_Login.show()
    sys.exit(app.exec_())
