# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'FormNhandien.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_FormNhandien(object):
    def setupUi(self, FormNhandien):
        FormNhandien.setObjectName("FormNhandien")
        FormNhandien.resize(950, 600)
        FormNhandien.setWindowFlags(QtCore.Qt.FramelessWindowHint)
        FormNhandien.setAttribute(QtCore.Qt.WA_TranslucentBackground)
        FormNhandien.setStyleSheet("QPushButton#bt_back{\n"
"background-color:rgba(2,65,118,255);\n"
"color:rgba(255,255,255,200);\n"
"border-radius:5px;\n"
"}\n"
"QPushButton#bt_back:pressed{\n"
"padding-left:5px;\n"
"padding-top:5px;\n"
"background-color:rgba(2,65,118,100);\n"
"background-position:calc(100%-10px)center;\n"
"}\n"
"QPushButton#bt_back:hover{\n"
"background-color:rgba(2,65,118,200);\n"
"}\n"
"QPushButton#bt_camera{\n"
"background-color:rgba(2,65,118,255);\n"
"color:rgba(255,255,255,200);\n"
"border-radius:5px;\n"
"}\n"
"QPushButton#bt_camera:pressed{\n"
"padding-left:5px;\n"
"padding-top:5px;\n"
"background-color:rgba(2,65,118,100);\n"
"background-position:calc(100%-10px)center;\n"
"}\n"
"QPushButton#bt_camera:hover{\n"
"background-color:rgba(2,65,118,200);\n"
"}\n"
"QPushButton#bt_start{\n"
"background-color:rgba(2,65,118,255);\n"
"color:rgba(255,255,255,200);\n"
"border-radius:5px;\n"
"}\n"
"QPushButton#bt_start:pressed{\n"
"padding-left:5px;\n"
"padding-top:5px;\n"
"background-color:rgba(2,65,118,100);\n"
"background-position:calc(100%-10px)center;\n"
"}\n"
"QPushButton#bt_start:hover{\n"
"background-color:rgba(2,65,118,200);\n"
"}\n"
"QPushButton#bt_end{\n"
"background-color:rgba(2,65,118,255);\n"
"color:rgba(255,255,255,200);\n"
"border-radius:5px;\n"
"}\n"
"QPushButton#bt_end:pressed{\n"
"padding-left:5px;\n"
"padding-top:5px;\n"
"background-color:rgba(2,65,118,100);\n"
"background-position:calc(100%-10px)center;\n"
"}\n"
"QPushButton#bt_end:hover{\n"
"background-color:rgba(2,65,118,200);\n"
"}\n"
"QPushButton#bt_xemlich{\n"
"background-color:rgba(2,65,118,255);\n"
"color:rgba(255,255,255,200);\n"
"border-radius:5px;\n"
"}\n"
"QPushButton#bt_xemlich:pressed{\n"
"padding-left:5px;\n"
"padding-top:5px;\n"
"background-color:rgba(2,65,118,100);\n"
"background-position:calc(100%-10px)center;\n"
"}\n"
"QPushButton#bt_xemlich:hover{\n"
"background-color:rgba(2,65,118,200);\n"
"}\n"
"QPushButton#bt_trogiup{\n"
"background-color:rgba(2,65,118,255);\n"
"color:rgba(255,255,255,200);\n"
"border-radius:5px;\n"
"}\n"
"QPushButton#bt_trogiup:pressed{\n"
"padding-left:5px;\n"
"padding-top:5px;\n"
"background-color:rgba(2,65,118,100);\n"
"background-position:calc(100%-10px)center;\n"
"}\n"
"QPushButton#bt_trogiup:hover{\n"
"background-color:rgba(2,65,118,200);\n"
"}")
        self.label = QtWidgets.QLabel(FormNhandien)
        self.label.setGeometry(QtCore.QRect(0, 0, 950, 600))
        self.label.setStyleSheet("border-image: url(:/backgroud/backgroud/1614776.jpg);\n"
"border-radius:5px;")
        self.label.setText("")
        self.label.setObjectName("label")
        self.Camera_Label = QtWidgets.QLabel(FormNhandien)
        self.Camera_Label.setGeometry(QtCore.QRect(20, 20, 531, 381))
        self.Camera_Label.setStyleSheet("border-image: url(:/backgroud/backgroud/9.jpg);\n"
"border- radius:5px;")
        self.Camera_Label.setText("")
        self.Camera_Label.setObjectName("Camera_Label")
        self.bt_camera = QtWidgets.QPushButton(FormNhandien)
        self.bt_camera.setGeometry(QtCore.QRect(210, 420, 100, 30))
        font = QtGui.QFont()
        font.setFamily("UVN Dzung Dakao")
        font.setPointSize(10)
        font.setItalic(True)
        self.bt_camera.setFont(font)
        self.bt_camera.setObjectName("bt_camera")
        self.gridLayoutWidget = QtWidgets.QWidget(FormNhandien)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(600, 10, 331, 69))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.TimeLabel = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.TimeLabel.setFont(font)
        self.TimeLabel.setStyleSheet("color: rgb(255, 255, 0);")
        self.TimeLabel.setScaledContents(False)
        self.TimeLabel.setOpenExternalLinks(True)
        self.TimeLabel.setObjectName("TimeLabel")
        self.horizontalLayout_3.addWidget(self.TimeLabel)
        self.Time_Lable = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Time_Lable.setFont(font)
        self.Time_Lable.setStyleSheet("color: rgb(255, 255, 0);")
        self.Time_Lable.setObjectName("Time_Lable")
        self.horizontalLayout_3.addWidget(self.Time_Lable)
        self.gridLayout.addLayout(self.horizontalLayout_3, 1, 0, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.DateLable = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.DateLable.setFont(font)
        self.DateLable.setStyleSheet("color: rgb(255, 255, 0);")
        self.DateLable.setObjectName("DateLable")
        self.horizontalLayout_2.addWidget(self.DateLable)
        self.Date_Lable = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Date_Lable.setFont(font)
        self.Date_Lable.setStyleSheet("color: rgb(255, 255, 0);")
        self.Date_Lable.setObjectName("Date_Lable")
        self.horizontalLayout_2.addWidget(self.Date_Lable)
        self.gridLayout.addLayout(self.horizontalLayout_2, 0, 0, 1, 1)
        self.groupBox = QtWidgets.QGroupBox(FormNhandien)
        self.groupBox.setGeometry(QtCore.QRect(600, 110, 331, 331))
        self.groupBox.setStyleSheet("color: rgb(255, 255, 0);\n"
"background-color:rgba(0,0,0,75);")
        self.groupBox.setObjectName("groupBox")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.groupBox)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 30, 311, 281))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_2 = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: rgb(255, 255, 0);")
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_4.addWidget(self.label_2)
        self.Ten_Label = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Ten_Label.setFont(font)
        self.Ten_Label.setObjectName("Ten_Label")
        self.horizontalLayout_4.addWidget(self.Ten_Label)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_4 = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_8.addWidget(self.label_4)
        self.Id_Label = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Id_Label.setFont(font)
        self.Id_Label.setObjectName("Id_Label")
        self.horizontalLayout_8.addWidget(self.Id_Label)
        self.verticalLayout.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_6 = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_9.addWidget(self.label_6)
        self.Trangthai_Label = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Trangthai_Label.setFont(font)
        self.Trangthai_Label.setObjectName("Trangthai_Label")
        self.horizontalLayout_9.addWidget(self.Trangthai_Label)
        self.verticalLayout.addLayout(self.horizontalLayout_9)
        self.bt_back = QtWidgets.QPushButton(FormNhandien)
        self.bt_back.setGeometry(QtCore.QRect(450, 550, 93, 28))
        font = QtGui.QFont()
        font.setFamily("UVN Dzung Dakao")
        font.setPointSize(10)
        font.setItalic(True)
        self.bt_back.setFont(font)
        self.bt_back.setStyleSheet("")
        self.bt_back.setObjectName("bt_back")
        self.bt_start = QtWidgets.QPushButton(FormNhandien)
        self.bt_start.setGeometry(QtCore.QRect(30, 480, 200, 30))
        font = QtGui.QFont()
        font.setFamily("UVN Dzung Dakao")
        font.setPointSize(10)
        font.setItalic(True)
        self.bt_start.setFont(font)
        self.bt_start.setObjectName("bt_start")
        self.bt_end = QtWidgets.QPushButton(FormNhandien)
        self.bt_end.setGeometry(QtCore.QRect(290, 480, 200, 30))
        font = QtGui.QFont()
        font.setFamily("UVN Dzung Dakao")
        font.setPointSize(10)
        font.setItalic(True)
        self.bt_end.setFont(font)
        self.bt_end.setObjectName("bt_end")
        self.bt_xemlich = QtWidgets.QPushButton(FormNhandien)
        self.bt_xemlich.setGeometry(QtCore.QRect(630, 480, 100, 30))
        font = QtGui.QFont()
        font.setFamily("UVN Dzung Dakao")
        font.setPointSize(10)
        font.setItalic(True)
        self.bt_xemlich.setFont(font)
        self.bt_xemlich.setObjectName("bt_xemlich")
        self.bt_trogiup = QtWidgets.QPushButton(FormNhandien)
        self.bt_trogiup.setGeometry(QtCore.QRect(810, 480, 100, 30))
        font = QtGui.QFont()
        font.setFamily("UVN Dzung Dakao")
        font.setPointSize(10)
        font.setItalic(True)
        self.bt_trogiup.setFont(font)
        self.bt_trogiup.setObjectName("bt_trogiup")

        self.retranslateUi(FormNhandien)
        QtCore.QMetaObject.connectSlotsByName(FormNhandien)

    def retranslateUi(self, FormNhandien):
        _translate = QtCore.QCoreApplication.translate
        FormNhandien.setWindowTitle(_translate("FormNhandien", "Form"))
        self.bt_camera.setText(_translate("FormNhandien", "Bật camera"))
        self.TimeLabel.setText(_translate("FormNhandien", "Time:"))
        self.Time_Lable.setText(_translate("FormNhandien", "-"))
        self.DateLable.setText(_translate("FormNhandien", "Date:"))
        self.Date_Lable.setText(_translate("FormNhandien", "-"))
        self.groupBox.setTitle(_translate("FormNhandien", "Thông tin:"))
        self.label_2.setText(_translate("FormNhandien", "Tên:"))
        self.Ten_Label.setText(_translate("FormNhandien", "-"))
        self.label_4.setText(_translate("FormNhandien", "ID:"))
        self.Id_Label.setText(_translate("FormNhandien", "-"))
        self.label_6.setText(_translate("FormNhandien", "Trạng thái:"))
        self.Trangthai_Label.setText(_translate("FormNhandien", "-"))
        self.bt_back.setText(_translate("FormNhandien", "Back"))
        self.bt_start.setText(_translate("FormNhandien", "Bắt đầu "))
        self.bt_end.setText(_translate("FormNhandien", "Kết thúc"))
        self.bt_xemlich.setText(_translate("FormNhandien", "Xem lịch"))
        self.bt_trogiup.setText(_translate("FormNhandien", "Trợ giúp"))
import res_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    FormNhandien = QtWidgets.QWidget()
    ui = Ui_FormNhandien()
    ui.setupUi(FormNhandien)
    FormNhandien.show()
    sys.exit(app.exec_())
