# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'FormUpdate2.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(800, 500)
        Form.setWindowFlags(QtCore.Qt.FramelessWindowHint)
        Form.setAttribute(QtCore.Qt.WA_TranslucentBackground)
        Form.setStyleSheet("QPushButton#bt_hienthi{\n"
"background-color:rgba(2,65,118,255);\n"
"color:rgba(255,255,255,200);\n"
"border-radius:5px;\n"
"}\n"
"QPushButton#bt_hienthi:pressed{\n"
"padding-left:5px;\n"
"padding-top:5px;\n"
"background-color:rgba(2,65,118,100);\n"
"background-position:calc(100%-10px)center;\n"
"}\n"
"QPushButton#bt_hienthi:hover{\n"
"background-color:rgba(2,65,118,200);\n"
"}\n"
"QPushButton#bt_xoa{\n"
"background-color:rgba(2,65,118,255);\n"
"color:rgba(255,255,255,200);\n"
"border-radius:5px;\n"
"}\n"
"QPushButton#bt_xoa:pressed{\n"
"padding-left:5px;\n"
"padding-top:5px;\n"
"background-color:rgba(2,65,118,100);\n"
"background-position:calc(100%-10px)center;\n"
"}\n"
"QPushButton#bt_xoa:hover{\n"
"background-color:rgba(2,65,118,200);\n"
"}\n"
"QPushButton#bt_back{\n"
"background-color:rgba(2,65,118,255);\n"
"color:rgba(255,255,255,200);\n"
"border-radius:5px;\n"
"}\n"
"QPushButton#bt_back:pressed{\n"
"padding-left:5px;\n"
"padding-top:5px;\n"
"background-color:rgba(2,65,118,100);\n"
"background-position:calc(100%-10px)center;\n"
"}\n"
"QPushButton#bt_back:hover{\n"
"background-color:rgba(2,65,118,200);\n"
"}\n"
"QPushButton#bt_timkiem{\n"
"background-color:rgba(2,65,118,255);\n"
"color:rgba(255,255,255,200);\n"
"border-radius:5px;\n"
"}\n"
"QPushButton#bt_timkiem:pressed{\n"
"padding-left:5px;\n"
"padding-top:5px;\n"
"background-color:rgba(2,65,118,100);\n"
"background-position:calc(100%-10px)center;\n"
"}\n"
"QPushButton#bt_timkiem:hover{\n"
"background-color:rgba(2,65,118,200);\n"
"}")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(0, 0, 800, 500))
        self.label.setStyleSheet("border-image: url(:/backgroud/backgroud/futuristic_cpu.jpg);\n"
"border- radius: 5px;")
        self.label.setText("")
        self.label.setObjectName("label")
        self.tableWidget = QtWidgets.QTableWidget(Form)
        self.tableWidget.setGeometry(QtCore.QRect(20, 50, 480, 340))
        self.tableWidget.setStyleSheet("")
        self.tableWidget.setRowCount(5)
        self.tableWidget.setColumnCount(6)
        self.tableWidget.setObjectName("tableWidget")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(50, 20, 241, 21))
        font = QtGui.QFont()
        font.setFamily("UVN Dzung Dakao")
        font.setPointSize(12)
        font.setItalic(True)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: rgb(255, 255, 0);")
        self.label_2.setObjectName("label_2")
        self.bt_hienthi = QtWidgets.QPushButton(Form)
        self.bt_hienthi.setGeometry(QtCore.QRect(140, 420, 231, 28))
        font = QtGui.QFont()
        font.setFamily("UVN Dzung Dakao")
        font.setPointSize(10)
        font.setItalic(True)
        self.bt_hienthi.setFont(font)
        self.bt_hienthi.setObjectName("bt_hienthi")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(580, 10, 171, 51))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color: rgb(255, 255, 0);")
        self.label_3.setObjectName("label_3")
        self.bt_back = QtWidgets.QPushButton(Form)
        self.bt_back.setGeometry(QtCore.QRect(670, 440, 93, 28))
        font = QtGui.QFont()
        font.setFamily("UVN Dzung Dakao")
        font.setPointSize(10)
        font.setItalic(True)
        self.bt_back.setFont(font)
        self.bt_back.setObjectName("bt_back")
        self.line_id = QtWidgets.QLineEdit(Form)
        self.line_id.setGeometry(QtCore.QRect(570, 60, 180, 25))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.line_id.setFont(font)
        self.line_id.setStyleSheet("background-color:rgba(0,0,0,0);\n"
"border:none;\n"
"border-bottom:2px solid rgba(46,82,101,200);\n"
"color:rgba(0,0,0,240);\n"
"padding-bottom:7px;")
        self.line_id.setObjectName("line_id")
        self.bt_xoa = QtWidgets.QPushButton(Form)
        self.bt_xoa.setGeometry(QtCore.QRect(600, 130, 101, 28))
        font = QtGui.QFont()
        font.setFamily("UVN Dzung Dakao")
        font.setPointSize(10)
        font.setItalic(True)
        self.bt_xoa.setFont(font)
        self.bt_xoa.setObjectName("bt_xoa")
        self.error = QtWidgets.QLabel(Form)
        self.error.setGeometry(QtCore.QRect(560, 90, 211, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.error.setFont(font)
        self.error.setStyleSheet("color: rgb(255, 255, 0);")
        self.error.setText("")
        self.error.setObjectName("error")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(530, 230, 251, 161))
        self.label_4.setStyleSheet("background-color:rgba(0,0,0,75);")
        self.label_4.setText("")
        self.label_4.setObjectName("label_4")
        self.bt_timkiem = QtWidgets.QPushButton(Form)
        self.bt_timkiem.setGeometry(QtCore.QRect(600, 360, 101, 28))
        font = QtGui.QFont()
        font.setFamily("UVN Dzung Dakao")
        font.setPointSize(10)
        font.setItalic(True)
        self.bt_timkiem.setFont(font)
        self.bt_timkiem.setObjectName("bt_timkiem")
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setGeometry(QtCore.QRect(580, 230, 171, 51))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("color: rgb(255, 255, 0);")
        self.label_5.setObjectName("label_5")
        self.line_id_2 = QtWidgets.QLineEdit(Form)
        self.line_id_2.setGeometry(QtCore.QRect(560, 280, 180, 25))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.line_id_2.setFont(font)
        self.line_id_2.setStyleSheet("background-color:rgba(0,0,0,0);\n"
"border:none;\n"
"border-bottom:2px solid rgba(46,82,101,200);\n"
"color: rgb(255, 255, 0);\n"
"padding-bottom:7px;")
        self.line_id_2.setObjectName("line_id_2")
        self.error_2 = QtWidgets.QLabel(Form)
        self.error_2.setGeometry(QtCore.QRect(550, 320, 211, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.error_2.setFont(font)
        self.error_2.setStyleSheet("color: rgb(255, 255, 0);")
        self.error_2.setText("")
        self.error_2.setObjectName("error_2")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_2.setText(_translate("Form", "Danh sách sinh viên:"))
        self.bt_hienthi.setText(_translate("Form", "Hiển thị danh sách"))
        self.label_3.setText(_translate("Form", "Nhập ID đối tượng cần xóa"))
        self.bt_back.setText(_translate("Form", "Thoát"))
        self.line_id.setPlaceholderText(_translate("Form", "ID"))
        self.bt_xoa.setText(_translate("Form", "Xóa"))
        self.bt_timkiem.setText(_translate("Form", "Tìm kiếm"))
        self.label_5.setText(_translate("Form", "Nhập ID đối tượng cần tìm"))
        self.line_id_2.setPlaceholderText(_translate("Form", "ID"))
import res_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
